'use strict'

/*
|--------------------------------------------------------------------------
| ProdutoCaracteristicaSeeder
|--------------------------------------------------------------------------
|
| Make use of the Factory instance to seed database with dummy data or
| make use of Lucid models directly.
|
*/

/** @type {import('@adonisjs/lucid/src/Factory')} */
const Factory = use('Factory')

const ProdutoCaracteristica = use('App/Models/ProdutoCaracteristica')

class ProdutoCaracteristicaSeeder {
  async run () {
    await ProdutoCaracteristica.createMany([

      {produto_id: 1, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 1, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 1, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 1, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 1, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 1, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 1, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 1, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 1, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 1, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},
      
      {produto_id: 2, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 2, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 2, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 2, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 2, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 2, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 2, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 2, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 2, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 2, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 3, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 3, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 3, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 3, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 3, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 3, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 3, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 3, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 3, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 3, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 4, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 4, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 4, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 4, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 4, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 4, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 4, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 4, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 4, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 4, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 5, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 5, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 5, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 5, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 5, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 5, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 5, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 5, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 5, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 5, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 6, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 6, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 6, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 6, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 6, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 6, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 6, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 6, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 6, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 6, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 7, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 7, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 7, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 7, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 7, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 7, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 7, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 7, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 7, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 7, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 8, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 8, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 8, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 8, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 8, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 8, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 8, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 8, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 8, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 8, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 9, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 9, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 9, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 9, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 9, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 9, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 9, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 9, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 9, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 9, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 10, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 10, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 10, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 10, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 10, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 10, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 10, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 10, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 10, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 10, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 11, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 11, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 11, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 11, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 11, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 11, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 11, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 11, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 11, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 11, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 12, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 12, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 12, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 12, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 12, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 12, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 12, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 12, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 12, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 12, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 13, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 13, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 13, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 13, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 13, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 13, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 13, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 13, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 13, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 13, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 14, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 14, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 14, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 14, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 14, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 14, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 14, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 14, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 14, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 14, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 15, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 15, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 15, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 15, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 15, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 15, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 15, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 15, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 15, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 15, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 16, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 16, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 16, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 16, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 16, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 16, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 16, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 16, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 16, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 16, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 17, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 17, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 17, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 17, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 17, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 17, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 17, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 17, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 17, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 17, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 18, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 18, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 18, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 18, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 18, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 18, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 18, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 18, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 18, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 18, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 19, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 19, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 19, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 19, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 19, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 19, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 19, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 19, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 19, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 19, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 21, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 21, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 21, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 21, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 21, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 21, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 21, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 21, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 21, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 21, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 20, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 20, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 20, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 20, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 20, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 20, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 20, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 20, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 20, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 20, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 22, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 22, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 22, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 22, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 22, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 22, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 22, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 22, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 22, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 22, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 23, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 23, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 23, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 23, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 23, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 23, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 23, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 23, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 23, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 23, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 24, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 24, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 24, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 24, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 24, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 24, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 24, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 24, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 24, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 24, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 25, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 25, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 25, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 25, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 25, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 25, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 25, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 25, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 25, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 25, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 26, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 26, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 26, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 26, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 26, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 26, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 26, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 26, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 26, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 26, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 27, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 27, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 27, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 27, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 27, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 27, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 27, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 27, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 27, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 27, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},

      {produto_id: 28, caracteristica_id: 1, valor: 'Barra'},
      {produto_id: 28, caracteristica_id: 2, valor: 'Branco'},
      {produto_id: 28, caracteristica_id: 3, valor: 'MP3 Player'},
      {produto_id: 28, caracteristica_id: 4, valor: '128 GB (Total, sendo uma parte usada para o sistema operacional e aplicativos pré-instalados)'},
      {produto_id: 28, caracteristica_id: 5, valor: 'Sim'},
      {produto_id: 28, caracteristica_id: 6, valor: 'Sim'},
      {produto_id: 28, caracteristica_id: 7, valor: 'A13 Bionic Neural Engine de terceira geração'},
      {produto_id: 28, caracteristica_id: 8, valor: 'Sim'},
      {produto_id: 28, caracteristica_id: 9, valor: 'SMS, MMS, E-mail'},
      {produto_id: 28, caracteristica_id: 10, valor: '- Tela LCD Liquid Retina HD de 6.1 polegadas - Resistência à água e poeira (até dois metros por até 30 minutos, IP68)- Sistema de câmera dupla com câmeras ultra-angular e grande-angular de 12 MP; modo Noite, modo Retrato e vídeo 4K a 60 qps- Câmera TrueDepth frontal de 12 MP com modo Retrato, vídeo 4K e câmera lenta- Face ID para autenticação segura e Apple Pay- Chip A13 Bionic com Neural Engine de terceira geração- Compatível com recarga rápida- Recarga sem fio- Modelo MHDJ3BR/A'},
      

    ])
  }
}

module.exports = ProdutoCaracteristicaSeeder
